
module.exports = [
  { src: `start`,
    publicPath: ``,
    privatePath: `/verse.xo` },
  { src: `drive-js`,
    publicPath: ``,
    privatePath: `/verse.xo` },
  { src: `stone`,
    publicPath: ``,
    privatePath: `/verse.xo` },
  { src: `start`,
    publicPath: `/hatch/bound`,
    privatePath: `/hatch/bound/verse.xo` },
  { src: `start`,
    publicPath: `/hatch/build`,
    privatePath: `/hatch/build/verse.xo` },
  { src: `start`,
    publicPath: `/hatch/cause`,
    privatePath: `/hatch/cause/verse.xo` },
  { src: `start`,
    publicPath: `/hatch/cause/build`,
    privatePath: `/hatch/cause/build/verse.xo` },
  { src: `start`,
    publicPath: `/hatch/cause/catch`,
    privatePath: `/hatch/cause/catch/verse.xo` },
  { src: `start`,
    publicPath: `/hatch/cause/mount`,
    privatePath: `/hatch/cause/mount/verse.xo` },
  { src: `start`,
    publicPath: `/hatch/cause/state`,
    privatePath: `/hatch/cause/state/verse.xo` },
  { src: `start`,
    publicPath: `/hatch/fetch`,
    privatePath: `/hatch/fetch/verse.xo` },
  { src: `start`,
    publicPath: `/hatch/field`,
    privatePath: `/hatch/field/verse.xo` },
  { src: `start`,
    publicPath: `/hatch/field/state`,
    privatePath: `/hatch/field/state/verse.xo` },
  { src: `start`,
    publicPath: `/hatch/force`,
    privatePath: `/hatch/force/verse.xo` },
  { src: `start`,
    publicPath: `/hatch/force/mount`,
    privatePath: `/hatch/force/mount/verse.xo` },
  { src: `start`,
    publicPath: `/hatch/hatch/catch`,
    privatePath: `/hatch/hatch/catch/verse.xo` },
  { src: `start`,
    publicPath: `/hatch/hatch/match`,
    privatePath: `/hatch/hatch/match/verse.xo` },
  { src: `start`,
    publicPath: `/hatch/reach`,
    privatePath: `/hatch/reach/verse.xo` },
  { src: `start`,
    publicPath: `/hatch/stack`,
    privatePath: `/hatch/stack/verse.xo` },
  { src: `start`,
    publicPath: `/hatch/theme`,
    privatePath: `/hatch/theme/verse.xo` },
  { src: `start`,
    publicPath: `/hatch/verse`,
    privatePath: `/hatch/verse/verse.xo` },
  { src: `start`,
    publicPath: `/hatch/match`,
    privatePath: `/hatch/match/verse.xo` },
  { src: `start`,
    publicPath: `/hatch/state`,
    privatePath: `/hatch/state/verse.xo` },
  { src: `start`,
    publicPath: `/hatch/hatch`,
    privatePath: `/hatch/hatch/verse.xo` },
  { src: `start`,
    publicPath: `/field/cloud`,
    privatePath: `/field/cloud/verse.xo` },
  { src: `start`,
    publicPath: `/field/shard/32`,
    privatePath: `/field/shard/32/verse.xo` },
  { src: `start`,
    publicPath: `/field/shard`,
    privatePath: `/field/shard/verse.xo` },
  { src: `start`,
    publicPath: `/field/cloud/house`,
    privatePath: `/field/cloud/house/verse.xo` },
  { src: `start`,
    publicPath: `/field/stack`,
    privatePath: `/field/stack/verse.xo` },
  { src: `start`,
    publicPath: `/field/stack/store`,
    privatePath: `/field/stack/store/verse.xo` },
  { src: `start`,
    publicPath: `/field/stack/store/theme`,
    privatePath: `/field/stack/store/theme/verse.xo` },
  { src: `start`,
    publicPath: `/field/track`,
    privatePath: `/field/track/verse.xo` },
  { src: `start`,
    publicPath: `/field/track/train`,
    privatePath: `/field/track/train/verse.xo` },
  { src: `start`,
    publicPath: `/field/track/train/crate`,
    privatePath: `/field/track/train/crate/verse.xo` },
  { src: `start`,
    publicPath: `/field/track/drive`,
    privatePath: `/field/track/drive/verse.xo` },
  { src: `start`,
    publicPath: `/field/track/march`,
    privatePath: `/field/track/march/verse.xo` },
  { src: `start`,
    publicPath: `/field/state`,
    privatePath: `/field/state/verse.xo` },
  { src: `start`,
    publicPath: `/field/brand`,
    privatePath: `/field/brand/verse.xo` },
  { src: `start`,
    publicPath: `/field/chain`,
    privatePath: `/field/chain/verse.xo` },
  { src: `start`,
    publicPath: `/field/chain/block`,
    privatePath: `/field/chain/block/verse.xo` },
  { src: `start`,
    publicPath: `/field/fetch`,
    privatePath: `/field/fetch/verse.xo` },
  { src: `start`,
    publicPath: `/field/fetch/catch`,
    privatePath: `/field/fetch/catch/verse.xo` },
  { src: `start`,
    publicPath: `/field/force`,
    privatePath: `/field/force/verse.xo` },
  { src: `start`,
    publicPath: `/field/force/cause`,
    privatePath: `/field/force/cause/verse.xo` },
  { src: `start`,
    publicPath: `/field/force/cause/mount`,
    privatePath: `/field/force/cause/mount/verse.xo` },
  { src: `start`,
    publicPath: `/field/force/cause/catch`,
    privatePath: `/field/force/cause/catch/verse.xo` },
  { src: `start`,
    publicPath: `/field/field`,
    privatePath: `/field/field/verse.xo` },
  { src: `start`,
    publicPath: `/field/field/state`,
    privatePath: `/field/field/state/verse.xo` },
  { src: `start`,
    publicPath: `/field/hatch`,
    privatePath: `/field/hatch/verse.xo` },
  { src: `start`,
    publicPath: `/field/hatch/match`,
    privatePath: `/field/hatch/match/verse.xo` },
  { src: `start`,
    publicPath: `/field/count`,
    privatePath: `/field/count/verse.xo` },
  { src: `start`,
    publicPath: `/field/write`,
    privatePath: `/field/write/verse.xo` },
  { src: `start`,
    publicPath: `/field/write/block`,
    privatePath: `/field/write/block/verse.xo` },
  { src: `start`,
    publicPath: `/field/match`,
    privatePath: `/field/match/verse.xo` },
  { src: `start`,
    publicPath: `/field/build`,
    privatePath: `/field/build/verse.xo` },
  { src: `start`,
    publicPath: `/field/store`,
    privatePath: `/field/store/verse.xo` },
  { src: `start`,
    publicPath: `/force/check`,
    privatePath: `/force/check/verse.xo` },
  { src: `start`,
    publicPath: `/force/store`,
    privatePath: `/force/store/verse.xo` },
  { src: `start`,
    publicPath: `/force/track`,
    privatePath: `/force/track/verse.xo` },
  { src: `start`,
    publicPath: `/force/count`,
    privatePath: `/force/count/verse.xo` },
  { src: `start`,
    publicPath: `/force/drive`,
    privatePath: `/force/drive/verse.xo` },
  { src: `start`,
    publicPath: `/force/chain`,
    privatePath: `/force/chain/verse.xo` },
  { src: `start`,
    publicPath: `/field/stick/chain`,
    privatePath: `/field/stick/chain/verse.xo` },
  { src: `start`,
    publicPath: `/field/stick/hatch`,
    privatePath: `/field/stick/hatch/verse.xo` },
  { src: `start`,
    publicPath: `/force/stick/hatch`,
    privatePath: `/force/stick/hatch/verse.xo` },
  { src: `start`,
    publicPath: `/force/stick/chain`,
    privatePath: `/force/stick/chain/verse.xo` },
  { src: `start`,
    publicPath: `/force/stick`,
    privatePath: `/force/stick/verse.xo` },
  { src: `start`,
    publicPath: `/force/clock`,
    privatePath: `/force/clock/verse.xo` },
  { src: `start`,
    publicPath: `/force/write`,
    privatePath: `/force/write/verse.xo` },
  { src: `start`,
    publicPath: `/force/state/chain`,
    privatePath: `/force/state/chain/verse.xo` },
  { src: `start`,
    publicPath: `/force/state`,
    privatePath: `/force/state/verse.xo` },
  { src: `start`,
    publicPath: `/force/shard`,
    privatePath: `/force/shard/verse.xo` },
  { src: `start`,
    publicPath: `/force/force`,
    privatePath: `/force/force/verse.xo` },
  { src: `start`,
    publicPath: `/theme/build`,
    privatePath: `/theme/build/verse.xo` },
  { src: `start`,
    publicPath: `/theme/draft`,
    privatePath: `/theme/draft/verse.xo` },
  { src: `start`,
    publicPath: `/theme/hatch`,
    privatePath: `/theme/hatch/verse.xo` },
  { src: `start`,
    publicPath: `/theme/verse`,
    privatePath: `/theme/verse/verse.xo` },
  { src: `start`,
    publicPath: `/theme/match`,
    privatePath: `/theme/match/verse.xo` },
  { src: `start`,
    publicPath: `/theme/theme`,
    privatePath: `/theme/theme/verse.xo` },
  { src: `start`,
    publicPath: `/theme/field`,
    privatePath: `/theme/field/verse.xo` },
  { src: `start`,
    publicPath: `/theme/force`,
    privatePath: `/theme/force/verse.xo` },
  { src: `start`,
    publicPath: `/theme/force/mount`,
    privatePath: `/theme/force/mount/verse.xo` },
  { src: `start`,
    publicPath: `/front`,
    privatePath: `/front/verse.xo` },
  { src: `start`,
    publicPath: `/mount`,
    privatePath: `/mount/verse.xo` },
  { src: `drive-js`,
    publicPath: `/mount`,
    privatePath: `/mount/verse.xo` },
  { src: `stone`,
    publicPath: `/check`,
    privatePath: `/check/verse.xo` },
  { src: `stone`,
    publicPath: `/mount`,
    privatePath: `/mount/verse.xo` },
  { src: `drive-js`,
    publicPath: `/base`,
    privatePath: `/state/base/verse.xo` },
  { src: `drive-js`,
    publicPath: `/string`,
    privatePath: `/state/string/verse.xo` },
  { src: `drive-js`,
    publicPath: `/number`,
    privatePath: `/state/number/verse.xo` },
  { src: `drive-js`,
    publicPath: `/function`,
    privatePath: `/state/function/verse.xo` },
  { src: `drive-js`,
    publicPath: `/array`,
    privatePath: `/state/array/verse.xo` },
  { src: `drive-js`,
    publicPath: `/dataview`,
    privatePath: `/state/dataview/verse.xo` },
  { src: `drive-js`,
    publicPath: `/console`,
    privatePath: `/state/console/verse.xo` },
  { src: `drive-js`,
    publicPath: `/datetime`,
    privatePath: `/state/datetime/verse.xo` },
  { src: `drive-js`,
    publicPath: `/error`,
    privatePath: `/state/error/verse.xo` },
  { src: `drive-js`,
    publicPath: `/interval`,
    privatePath: `/state/interval/verse.xo` },
  { src: `drive-js`,
    publicPath: `/object`,
    privatePath: `/state/object/verse.xo` },
  { src: `drive-js`,
    publicPath: `/regex`,
    privatePath: `/state/regex/verse.xo` },
  { src: `drive-js`,
    publicPath: `/timeout`,
    privatePath: `/state/timeout/verse.xo` },
  { src: `drive-node`,
    publicPath: ``,
    privatePath: `/verse.xo` },
  { src: `drive-node`,
    publicPath: `/fs`,
    privatePath: `/state/fs/verse.xo` },
  { src: `drive-node`,
    publicPath: `/assert`,
    privatePath: `/state/assert/verse.xo` },
  { src: `drive-node`,
    publicPath: `/buffer`,
    privatePath: `/state/buffer/verse.xo` },
  { src: `drive-node`,
    publicPath: `/child-process`,
    privatePath: `/state/child-process/verse.xo` },
  { src: `drive-node`,
    publicPath: `/event`,
    privatePath: `/state/event/verse.xo` },
  { src: `drive-node`,
    publicPath: `/http`,
    privatePath: `/state/http/verse.xo` },
  { src: `drive-node`,
    publicPath: `/http2`,
    privatePath: `/state/http2/verse.xo` },
  { src: `drive-node`,
    publicPath: `/module`,
    privatePath: `/state/module/verse.xo` },
  { src: `drive-node`,
    publicPath: `/net`,
    privatePath: `/state/net/verse.xo` },
  { src: `drive-node`,
    publicPath: `/os`,
    privatePath: `/state/os/verse.xo` },
  { src: `drive-node`,
    publicPath: `/path`,
    privatePath: `/state/path/verse.xo` },
  { src: `drive-node`,
    publicPath: `/zlib`,
    privatePath: `/state/zlib/verse.xo` },
  { src: `drive-node`,
    publicPath: `/process`,
    privatePath: `/state/process/verse.xo` },
  { src: `drive-js`,
    publicPath: `/datetime`,
    privatePath: `/state/datetime/verse.xo` }
]
