
module.exports = [
  { src: `start`,
    publicPath: ``,
    privatePath: `/verse.xo` },
  { src: `write`,
    publicPath: ``,
    privatePath: `/verse.xo` },
  { src: `drive`,
    publicPath: ``,
    privatePath: `/verse.xo` },
  { src: `stone`,
    publicPath: ``,
    privatePath: `/verse.xo` },
  { src: `start`,
    publicPath: `/hatch/bound`,
    privatePath: `/stack/hatch/bound/verse.xo` },
  { src: `start`,
    publicPath: `/hatch/build`,
    privatePath: `/stack/hatch/build/verse.xo` },
  { src: `start`,
    publicPath: `/hatch/cause`,
    privatePath: `/stack/hatch/cause/verse.xo` },
  { src: `start`,
    publicPath: `/hatch/cause/build`,
    privatePath: `/stack/hatch/cause/build/verse.xo` },
  { src: `start`,
    publicPath: `/hatch/cause/catch`,
    privatePath: `/stack/hatch/cause/catch/verse.xo` },
  { src: `start`,
    publicPath: `/hatch/cause/mount`,
    privatePath: `/stack/hatch/cause/mount/verse.xo` },
  { src: `start`,
    publicPath: `/hatch/cause/state`,
    privatePath: `/stack/hatch/cause/state/verse.xo` },
  { src: `start`,
    publicPath: `/hatch/fetch`,
    privatePath: `/stack/hatch/fetch/verse.xo` },
  { src: `start`,
    publicPath: `/hatch/field`,
    privatePath: `/stack/hatch/field/verse.xo` },
  { src: `start`,
    publicPath: `/hatch/field/state`,
    privatePath: `/stack/hatch/field/state/verse.xo` },
  { src: `start`,
    publicPath: `/hatch/force`,
    privatePath: `/stack/hatch/force/verse.xo` },
  { src: `start`,
    publicPath: `/hatch/force/mount`,
    privatePath: `/stack/hatch/force/mount/verse.xo` },
  { src: `start`,
    publicPath: `/hatch/hatch/catch`,
    privatePath: `/stack/hatch/hatch/catch/verse.xo` },
  { src: `start`,
    publicPath: `/hatch/hatch/match`,
    privatePath: `/stack/hatch/hatch/match/verse.xo` },
  { src: `start`,
    publicPath: `/hatch/reach`,
    privatePath: `/stack/hatch/reach/verse.xo` },
  { src: `start`,
    publicPath: `/hatch/stack`,
    privatePath: `/stack/hatch/stack/verse.xo` },
  { src: `start`,
    publicPath: `/hatch/theme`,
    privatePath: `/stack/hatch/theme/verse.xo` },
  { src: `start`,
    publicPath: `/hatch/verse`,
    privatePath: `/stack/hatch/verse/verse.xo` },
  { src: `start`,
    publicPath: `/hatch/match`,
    privatePath: `/stack/hatch/match/verse.xo` },
  { src: `start`,
    publicPath: `/hatch/state`,
    privatePath: `/stack/hatch/state/verse.xo` },
  { src: `start`,
    publicPath: `/hatch/hatch`,
    privatePath: `/stack/hatch/hatch/verse.xo` },
  { src: `start`,
    publicPath: `/field/cloud`,
    privatePath: `/stack/field/cloud/verse.xo` },
  { src: `start`,
    publicPath: `/field/shard/32`,
    privatePath: `/stack/field/shard/32/verse.xo` },
  { src: `start`,
    publicPath: `/field/shard`,
    privatePath: `/stack/field/shard/verse.xo` },
  { src: `start`,
    publicPath: `/field/cloud/house`,
    privatePath: `/stack/field/cloud/house/verse.xo` },
  { src: `start`,
    publicPath: `/field/stack`,
    privatePath: `/stack/field/stack/verse.xo` },
  { src: `start`,
    publicPath: `/field/stack/store`,
    privatePath: `/stack/field/stack/store/verse.xo` },
  { src: `start`,
    publicPath: `/field/stack/store/theme`,
    privatePath: `/stack/field/stack/store/theme/verse.xo` },
  { src: `start`,
    publicPath: `/field/track`,
    privatePath: `/stack/field/track/verse.xo` },
  { src: `start`,
    publicPath: `/field/track/train`,
    privatePath: `/stack/field/track/train/verse.xo` },
  { src: `start`,
    publicPath: `/field/track/train/crate`,
    privatePath: `/stack/field/track/train/crate/verse.xo` },
  { src: `start`,
    publicPath: `/field/track/drive`,
    privatePath: `/stack/field/track/drive/verse.xo` },
  { src: `start`,
    publicPath: `/field/track/march`,
    privatePath: `/stack/field/track/march/verse.xo` },
  { src: `start`,
    publicPath: `/field/state`,
    privatePath: `/stack/field/state/verse.xo` },
  { src: `start`,
    publicPath: `/field/brand`,
    privatePath: `/stack/field/brand/verse.xo` },
  { src: `start`,
    publicPath: `/field/chain`,
    privatePath: `/stack/field/chain/verse.xo` },
  { src: `start`,
    publicPath: `/field/chain/block`,
    privatePath: `/stack/field/chain/block/verse.xo` },
  { src: `start`,
    publicPath: `/field/fetch`,
    privatePath: `/stack/field/fetch/verse.xo` },
  { src: `start`,
    publicPath: `/field/fetch/catch`,
    privatePath: `/stack/field/fetch/catch/verse.xo` },
  { src: `start`,
    publicPath: `/field/force`,
    privatePath: `/stack/field/force/verse.xo` },
  { src: `start`,
    publicPath: `/field/force/cause`,
    privatePath: `/stack/field/force/cause/verse.xo` },
  { src: `start`,
    publicPath: `/field/force/cause/mount`,
    privatePath: `/stack/field/force/cause/mount/verse.xo` },
  { src: `start`,
    publicPath: `/field/force/cause/catch`,
    privatePath: `/stack/field/force/cause/catch/verse.xo` },
  { src: `start`,
    publicPath: `/field/field`,
    privatePath: `/stack/field/field/verse.xo` },
  { src: `start`,
    publicPath: `/field/field/state`,
    privatePath: `/stack/field/field/state/verse.xo` },
  { src: `start`,
    publicPath: `/field/hatch`,
    privatePath: `/stack/field/hatch/verse.xo` },
  { src: `start`,
    publicPath: `/field/hatch/match`,
    privatePath: `/stack/field/hatch/match/verse.xo` },
  { src: `start`,
    publicPath: `/field/count`,
    privatePath: `/stack/field/count/verse.xo` },
  { src: `start`,
    publicPath: `/field/write`,
    privatePath: `/stack/field/write/verse.xo` },
  { src: `start`,
    publicPath: `/field/write/block`,
    privatePath: `/stack/field/write/block/verse.xo` },
  { src: `start`,
    publicPath: `/mount/stack`,
    privatePath: `/stack/mount/stack/verse.xo` },
  { src: `start`,
    publicPath: `/field/match`,
    privatePath: `/stack/field/match/verse.xo` },
  { src: `start`,
    publicPath: `/field/build`,
    privatePath: `/stack/field/build/verse.xo` },
  { src: `start`,
    publicPath: `/field/store`,
    privatePath: `/stack/field/store/verse.xo` },
  { src: `start`,
    publicPath: `/force/check`,
    privatePath: `/stack/force/check/verse.xo` },
  { src: `start`,
    publicPath: `/force/store`,
    privatePath: `/stack/force/store/verse.xo` },
  { src: `start`,
    publicPath: `/force/track`,
    privatePath: `/stack/force/track/verse.xo` },
  { src: `start`,
    publicPath: `/force/count`,
    privatePath: `/stack/force/count/verse.xo` },
  { src: `start`,
    publicPath: `/force/drive`,
    privatePath: `/stack/force/drive/verse.xo` },
  { src: `start`,
    publicPath: `/force/chain`,
    privatePath: `/stack/force/chain/verse.xo` },
  { src: `write`,
    publicPath: `/xo/trace`,
    privatePath: `/stack/xo/trace/verse.xo` },
  { src: `start`,
    publicPath: `/field/stick/chain`,
    privatePath: `/stack/field/stick/chain/verse.xo` },
  { src: `start`,
    publicPath: `/field/stick/hatch`,
    privatePath: `/stack/field/stick/hatch/verse.xo` },
  { src: `start`,
    publicPath: `/force/stick/hatch`,
    privatePath: `/stack/force/stick/hatch/verse.xo` },
  { src: `start`,
    publicPath: `/force/stick/chain`,
    privatePath: `/stack/force/stick/chain/verse.xo` },
  { src: `start`,
    publicPath: `/force/stick`,
    privatePath: `/stack/force/stick/verse.xo` },
  { src: `start`,
    publicPath: `/force/clock`,
    privatePath: `/stack/force/clock/verse.xo` },
  { src: `start`,
    publicPath: `/force/write`,
    privatePath: `/stack/force/write/verse.xo` },
  { src: `start`,
    publicPath: `/force/state/chain`,
    privatePath: `/stack/force/state/chain/verse.xo` },
  { src: `start`,
    publicPath: `/force/state`,
    privatePath: `/stack/force/state/verse.xo` },
  { src: `start`,
    publicPath: `/force/shard`,
    privatePath: `/stack/force/shard/verse.xo` },
  { src: `start`,
    publicPath: `/force/force`,
    privatePath: `/stack/force/force/verse.xo` },
  { src: `start`,
    publicPath: `/theme/build`,
    privatePath: `/stack/theme/build/verse.xo` },
  { src: `start`,
    publicPath: `/theme/draft`,
    privatePath: `/stack/theme/draft/verse.xo` },
  { src: `start`,
    publicPath: `/theme/hatch`,
    privatePath: `/stack/theme/hatch/verse.xo` },
  { src: `start`,
    publicPath: `/theme/verse`,
    privatePath: `/stack/theme/verse/verse.xo` },
  { src: `start`,
    publicPath: `/theme/match`,
    privatePath: `/stack/theme/match/verse.xo` },
  { src: `start`,
    publicPath: `/theme/theme`,
    privatePath: `/stack/theme/theme/verse.xo` },
  { src: `start`,
    publicPath: `/theme/field`,
    privatePath: `/stack/theme/field/verse.xo` },
  { src: `start`,
    publicPath: `/theme/force`,
    privatePath: `/stack/theme/force/verse.xo` },
  { src: `start`,
    publicPath: `/theme/force/mount`,
    privatePath: `/stack/theme/force/mount/verse.xo` },
  { src: `start`,
    publicPath: `/match`,
    privatePath: `/match/verse.xo` },
  { src: `start`,
    publicPath: `/mount`,
    privatePath: `/mount/verse.xo` },
  { src: `write`,
    publicPath: `/mount`,
    privatePath: `/mount/verse.xo` },
  { src: `drive`,
    publicPath: `/mount`,
    privatePath: `/mount/verse.xo` },
  { src: `stone`,
    publicPath: `/check`,
    privatePath: `/check/verse.xo` },
  { src: `stone`,
    publicPath: `/mount`,
    privatePath: `/mount/verse.xo` },
  { src: `drive`,
    publicPath: `/javascript/binding/base`,
    privatePath: `/stack/javascript/binding/base/verse.xo` },
  { src: `drive`,
    publicPath: `/javascript/binding/string`,
    privatePath: `/stack/javascript/binding/string/verse.xo` },
  { src: `drive`,
    publicPath: `/javascript/binding/number`,
    privatePath: `/stack/javascript/binding/number/verse.xo` },
  { src: `drive`,
    publicPath: `/javascript/binding/function`,
    privatePath: `/stack/javascript/binding/function/verse.xo` },
  { src: `drive`,
    publicPath: `/javascript/binding/array`,
    privatePath: `/stack/javascript/binding/array/verse.xo` },
  { src: `drive`,
    publicPath: `/javascript/binding/dataview`,
    privatePath: `/stack/javascript/binding/dataview/verse.xo` },
  { src: `drive`,
    publicPath: `/javascript/binding/console`,
    privatePath: `/stack/javascript/binding/console/verse.xo` },
  { src: `drive`,
    publicPath: `/javascript/binding/datetime`,
    privatePath: `/stack/javascript/binding/datetime/verse.xo` },
  { src: `drive`,
    publicPath: `/javascript/binding/error`,
    privatePath: `/stack/javascript/binding/error/verse.xo` },
  { src: `drive`,
    publicPath: `/javascript/binding/interval`,
    privatePath: `/stack/javascript/binding/interval/verse.xo` },
  { src: `drive`,
    publicPath: `/javascript/binding/object`,
    privatePath: `/stack/javascript/binding/object/verse.xo` },
  { src: `drive`,
    publicPath: `/javascript/binding/regex`,
    privatePath: `/stack/javascript/binding/regex/verse.xo` },
  { src: `drive`,
    publicPath: `/javascript/binding/timeout`,
    privatePath: `/stack/javascript/binding/timeout/verse.xo` },
  { src: `drive`,
    publicPath: `/node`,
    privatePath: `/stack/node/verse.xo` },
  { src: `drive`,
    publicPath: `/node/binding/fs`,
    privatePath: `/stack/node/binding/fs/verse.xo` },
  { src: `drive`,
    publicPath: `/node/binding/assert`,
    privatePath: `/stack/node/binding/assert/verse.xo` },
  { src: `drive`,
    publicPath: `/node/binding/buffer`,
    privatePath: `/stack/node/binding/buffer/verse.xo` },
  { src: `drive`,
    publicPath: `/node/binding/child-process`,
    privatePath: `/stack/node/binding/child-process/verse.xo` },
  { src: `drive`,
    publicPath: `/node/binding/event`,
    privatePath: `/stack/node/binding/event/verse.xo` },
  { src: `drive`,
    publicPath: `/node/binding/http`,
    privatePath: `/stack/node/binding/http/verse.xo` },
  { src: `drive`,
    publicPath: `/node/binding/http2`,
    privatePath: `/stack/node/binding/http2/verse.xo` },
  { src: `drive`,
    publicPath: `/node/binding/module`,
    privatePath: `/stack/node/binding/module/verse.xo` },
  { src: `drive`,
    publicPath: `/node/binding/net`,
    privatePath: `/stack/node/binding/net/verse.xo` },
  { src: `drive`,
    publicPath: `/node/binding/os`,
    privatePath: `/stack/node/binding/os/verse.xo` },
  { src: `drive`,
    publicPath: `/node/binding/path`,
    privatePath: `/stack/node/binding/path/verse.xo` },
  { src: `drive`,
    publicPath: `/node/binding/zlib`,
    privatePath: `/stack/node/binding/zlib/verse.xo` },
  { src: `drive`,
    publicPath: `/node/binding/process`,
    privatePath: `/stack/node/binding/process/verse.xo` },
  { src: `drive`,
    publicPath: `/node/mapping`,
    privatePath: `/stack/node/mapping/verse.xo` },
  { src: `drive`,
    publicPath: `/javascript/mapping`,
    privatePath: `/stack/javascript/mapping/verse.xo` },
  { src: `drive`,
    publicPath: `/javascript/binding/datetime`,
    privatePath: `/stack/javascript/binding/datetime/verse.xo` }
]
